<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <RootNamespace>RelayLobby.Server</RootNamespace>
    <AssemblyName>RelayLobby.Server</AssemblyName>
    <LangVersion>7.3</LangVersion>
    <Deterministic>true</Deterministic>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="System.Runtime.Serialization" />
    <Reference Include="System.ServiceModel" />
    <ProjectReference Include="../RelayLobby.Contracts/RelayLobby.Contracts.csproj" />
    <ProjectReference Include="../RelayLobby.Domain/RelayLobby.Domain.csproj" />
  </ItemGroup>
</Project>
